# Generated by Django 5.2.2 on 2025-06-05 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_number", models.IntegerField()),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=255)),
                ("total_net", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_tax", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item", models.CharField(max_length=255)),
                ("item_price", models.FloatField()),
                ("item_tax", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("total_net", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_tax", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="zero_downtime_migrations.order",
                    ),
                ),
            ],
        ),
    ]
