# Generated by Django 4.2.2 on 2023-07-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.IntegerField()),
                ('field2', models.IntegerField(null=True)),
                ('field3', models.IntegerField()),
                ('field4', models.IntegerField()),
            ],
        ),
    ]
